-- ==========================================
-- Supabase Schema Setup: hoa_reports Table
-- Project: HOA Document Auditor (Token Blocker Cache)
-- ==========================================

-- 1. Create the reports caching table
CREATE TABLE IF NOT EXISTS public.hoa_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_hash text NOT NULL UNIQUE,
    payload jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add description comments for database documentation
COMMENT ON TABLE public.hoa_reports IS 'Caches validated audit report payloads against cryptographic MD5 hashes of document packages to bypass live LLM API token costs.';
COMMENT ON COLUMN public.hoa_reports.document_hash IS 'Unique MD5 cryptographic string fingerprint of the ingested document collection.';
COMMENT ON COLUMN public.hoa_reports.payload IS 'The structured JSON representation of the final multi-agent compliance evaluation.';

-- 3. Create a unique index on the document_hash column for O(1) query lookup latency
CREATE INDEX IF NOT EXISTS idx_hoa_reports_hash ON public.hoa_reports USING btree (document_hash);

-- 4. Automatically manage updated_at timestamps
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_set_updated_at
    BEFORE UPDATE ON public.hoa_reports
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.hoa_reports ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies
-- Allow anyone to read cached audits (anonymous public reads to facilitate rapid loading)
CREATE POLICY "Allow public read access to cached reports" 
    ON public.hoa_reports 
    FOR SELECT 
    USING (true);

-- Allow authenticated service key or app client to insert fresh evaluations
CREATE POLICY "Allow authenticated client inserts for new hashes" 
    ON public.hoa_reports 
    FOR INSERT 
    WITH CHECK (true);